### ISSUE TITLE
Check accessibility of data-table

### ISSUE THREAD

**Issue by tonifisler** [swiss/styleguide#219]
![capture decran 2014-08-08 a 16 43 42](https://cloud.githubusercontent.com/assets/1708450/3858079/74ee84e0-1f0a-11e4-8434-85dd83d0fe85.png)

**Problem: Daten-Tabellen verfügen teils über keine funktionierenden Spalten- und/oder Zeilentitel**

In der folgenden Daten-Tabellen werden im ersten Block die Zeilentitel nicht gelesen beim Navigieren innerhalb der Tabelle. Zudem wird in der ganzen Tabelle die Überschrift der 2.Spalte („2007“) nicht als Spaltentitel vorgelesen. Die restlichen Zeilen- und Spalten-Titel funktionieren korrekt.

**Problem: Daten-Tabellen verfügen über falsche Zuweisungen von IDs und Headers**

Bei der Daten-Tabelle „Cycle table (pairs)“ auf (http://adminch.antistatique.net/base_layout_- _tables.html ) scheinen die Zuordnung der IDs zu den Header-Attributs nicht zu stimmen. Der Screenreader liest auch in der Spalte „unterstellte Arbeitsnehmer“ immer die Spaltenüberschrift „GAV“ und das Jahr in der Spaltenüberschrift vor.

**Comment by desobryc** [comment]
Will be resolved with SWG22 Tables comply with accessibility guidelines

**Comment by LeBenLeBen** [comment]
Tables accessibility has been reviewed and improved in version 3.0.0.
