### ISSUE TITLE
Heading not in a logical sequence

### ISSUE THREAD

**Issue by tonifisler** [swiss/styleguide#243]
We should not skip a heading (going from h1 directly to h3)

![capture d ecran 2014-08-08 a 16 11 06](https://cloud.githubusercontent.com/assets/1708450/3857657/dbb94692-1f05-11e4-8c1a-6d09de6165f0.png)

Was put wrongly in #137

**Comment by desobryc** [comment]
Will be solved with SWG-18

**Comment by LeBenLeBen** [comment]
Headings hierarchy has been reviewed in version 3.0.0.
