### ISSUE TITLE
[sub-issue] CRw: Shopping cart is wrongly read by the screenreader

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#276]
![image](https://cloud.githubusercontent.com/assets/7510842/5356619/c03168e2-7f9e-11e4-8d63-b0480c60c119.png)

The "Delete" Symbol in the shopping cart is read with "p" by screen readers.

==> Use ARIA "labelledby" for "delete" or a hidden text.
If you use ARIA check it out with the screen reader NVDA http://www.nvaccess.org/download/

**Comment by tonifisler** [comment]
Main issue is #340
