### ISSUE TITLE
Single images will not be scaled and overlays their boxes.

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#283]
Description: Single images will not be scaled and overlays their boxes.

Browser: IE9, IE10, FF

Link: https://www.webguidelines.admin.ch/content_modules_-_multimedia.html

For further information or if you have any questions please do not hesitate to contact me. lukas.jaborsky@namics.com

Wrong: 
![lightbox_wrong](https://cloud.githubusercontent.com/assets/3909997/5204533/769fedba-7590-11e4-8bc9-8a22409a5126.PNG)

Right
![lightbox_right](https://cloud.githubusercontent.com/assets/3909997/5204538/7d58a1f6-7590-11e4-85bd-b7cb8c914389.PNG)

**Comment by zufrieden** [comment]
reviewed
