### ISSUE TITLE
Missing date-time picker in the input field (date)

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#286]
Description: Missing date-time picker in the input field (date). 

Browser: all

Link: https://www.webguidelines.admin.ch/pages/forms.html

For further information or if you have any questions please do not hesitate to contact me. lukas.jaborsky@namics.com

**Comment by zufrieden** [comment]
Exemple shown is chrome native date picker. 
We added an input type date.

**Comment by LukasJaborsky** [comment]
It was the solution. Thank you.
