### ISSUE TITLE
Arrow-icons behaves incorrectly for some accordion-components.

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#287]
Description: Arrow-icons behaves incorrectly for some accordion-components. Some arrows don't change when folding parts of a accordion. The failure occurs if the accordion has to or more parts. 

Link: http://swiss.github.io/styleguide/content_modules_-_content_containers.html#c-dropdown-box

Browser: all 

For further information or if you have any questions please do not hesitate to contact me. lukas.jaborsky@namics.com

Screenshot: 
![accordion_icon_wrong](https://cloud.githubusercontent.com/assets/3909997/5216367/8d8faa04-7632-11e4-80f8-8b4855fc7e16.png)

**Comment by tonifisler** [comment]
I can't reproduce this issue. Tested on several browsers.

I updated the collapsibles example to include several elements. Please report here if you encounter this bug again.
