### ISSUE TITLE
CRw: Two Header menus aren't read correctly

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#297]
![image](https://cloud.githubusercontent.com/assets/7510842/5362899/7f668728-7fd7-11e4-9446-285677d5409c.png)

The hierarchy of the 4 elements is wrong - all elements are on the same level (Screen reader reads: list one of four)
Both dropdowns are concerned (that means "Federal Administration" too)
==> Use a nested list (Department: EDI is a list and the 3 items are a second list)

Incorrect display on: http://swiss.github.io/styleguide/navigation_modules_-_header.html#a-header-logo
![image](https://cloud.githubusercontent.com/assets/7510842/5378453/98517cbc-808a-11e4-9158-3d2adbe06be7.png)

**Comment by tonifisler** [comment]
You can now use this markup:

```html
<li class="dropdown">
  <a href="#" id="service-dropdown" class="dropdown-toggle" data-toggle="dropdown"><span class="icon icon--right"></span> Departement: EDI</a>
  <ul class="dropdown-menu" role="menu" aria-labelledby="service-dropdown">
    <li class="dropdown-header">
      <a href="#">Departement: EDI</a>
      <ul>
        <li><a href="#">DEZA: Direktion für Entwicklung und Zusammenarbeit</a></li>
        <li><a href="#">Schweizer Beitrag an die erweiterte EU</a></li>
        <li><a href="#">Integrationsbüros</a></li>
      </ul>
    </li>
  </ul>
</li>
```
