### ISSUE TITLE
CRw: No keyboard tabbing with dropdown / No annunciation "expanded" for Screen readers

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#299]
![image](https://cloud.githubusercontent.com/assets/7510842/5379334/c84380fe-8090-11e4-8e9b-f17226199d74.png)

With keyboard tabbing the link "animal" is not selectable.
==> make it accessible for tabbing

Screen reader: When the link "animals" is open, there is no "expanded" announced.
==> Use ARIA "labelledby" or a hidden text.
If you use ARIA check it out with the screen reader NVDA http://www.nvaccess.org/download/

**Comment by tonifisler** [comment]
Please refer to http://webaim.org/articles/nvda/ for table navigation. You don't navigate in a table with tab.

I've transformed the collapse link in a `<a/>` tag to make it selectable with tab though and fixed a lot of issues that way.

Nevertheless, I think this kind of collapsible link in a table row is anything but a good practice if you want an accessible table...
