### ISSUE TITLE
[sub-issue] CRw: Enter button in search field is read as "S-Button"

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#311]
![image](https://cloud.githubusercontent.com/assets/7510842/5394398/0ec2b430-813d-11e4-8700-cabee91bf1b8.png)

Screen reader: The search button is announced with "S-Schalter" (S-Button)
==> Use ARIA "labelledby" or a hidden text for "Search"
If you use ARIA check it out with the screen reader NVDA http://www.nvaccess.org/download/

**Comment by tonifisler** [comment]
Main issue is #340

**Comment by tonifisler** [comment]
Pseudo-class. Closing.
