### ISSUE TITLE
CRw: Error message is ignored by the screenreader in the passoword field

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#315]
![image](https://cloud.githubusercontent.com/assets/7510842/5227203/56241eb2-76f8-11e4-9dbe-d7b34d67fbd2.png)

The error message here http://swiss.github.io/styleguide/base_layout_-_forms_elements.html#a-fieldsets is ignored by the screenreader. See #255

**Comment by desobryc** [comment]
Will be resolved with SWG-18
