### ISSUE TITLE
Frutiger fonts should not be hosted on github

### ISSUE THREAD

**Issue by stibos** [swiss/styleguide#317]
Hi guys

Nice to see Switzerland going on github! 

Plz take care to the fonts hosted here. Frutigers Neue is proprietary, not open and must not be made public...

Cheers, Stefan

**Comment by bit-pro-iew-eui** [comment]
We need to rediscuss if we want to change the Frutiger font to an open source font for the webguidelines. There are open-source fonts for web, which are similar to Frutiger and are for free.

**Comment by bit-pro-iew-eui** [comment]
The discussion will be followed on #525

**Comment by mbruellmann** [comment]
see issue #525
