### ISSUE TITLE
Distance in between checkboxes and text is wrong in search results.

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#318]
Description: Distance in between checkboxes an text is wrong in search results.

Link: http://swiss.github.io/styleguide/content_modules_-_search.html?#

Browser: all 

For further information or if you have any questions please do not hesitate to contact me. lukas.jaborsky@namics.com

Screenshot: 
![search_results_wrong](https://cloud.githubusercontent.com/assets/3909997/5263955/049c162a-7a37-11e4-802b-0db84a344df7.PNG)

**Comment by zufrieden** [comment]
reviewed
