### ISSUE TITLE
[icons] Icon in download list are shown twice. 

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#319]
Description: Icon in download list (general document) are shown twice. 

Link: http://swiss.github.io/styleguide/content_modules_-_functions.html

Browser: IE9

For further information or if you have any questions please do not hesitate to contact me. lukas.jaborsky@namics.com

Screenshot: 
![icon_shown_twice](https://cloud.githubusercontent.com/assets/3909997/5264358/67ff93f6-7a3a-11e4-91e2-9304c086e565.png)

**Comment by zufrieden** [comment]
Reviewed and closed
