### ISSUE TITLE
[typo] Faux bold on elements using Frutiger font

### ISSUE THREAD

**Issue by LeBenLeBen** [swiss/styleguide#322]
For example on tables, `th` element gets a bold font-weight (by the browser or by Bootstrap .table-* classes).

Since you defined Frutiger styles as separated fonts (Frutiger Neue Bold, Frutiger Neue Italic, …) the text is displayed using a _faux_ bold:

![capture d ecran 2014-12-05 a 11 19 11](https://cloud.githubusercontent.com/assets/793344/5314270/c3805688-7c70-11e4-85fb-722eb9c2df99.png)

Here it is with the real Frutiger Neue Bold:

![capture d ecran 2014-12-05 a 11 20 23](https://cloud.githubusercontent.com/assets/793344/5314273/cd6d1320-7c70-11e4-9108-5059e3e84336.png)

I’d personally make one font-face declaration with different variations so the variants get applied automatically. Would it be a problem?

**Comment by Yago** [comment]
@tonifisler well done :+1:
