### ISSUE TITLE
Anchor link for context information when placed at the bottom

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#327]
It should be possible to set an anchor link for the context information which is also shown when the fourth column is shown at the bottom of the page (Meaning for tablet and smartphone). 

@zufrieden please integrate this in the offer for Monday and if you need more details call me thank you.

**Comment by zufrieden** [comment]
You'll see it on this page http://swiss.github.io/styleguide/pages/detail.html

**Comment by desobryc** [comment]
Ok, thank you. 

The behavior is not fully ok, as in some case the context column is already at the bottom but no anchor link is displayed

![image](https://cloud.githubusercontent.com/assets/7644740/5659613/6458de72-9715-11e4-9348-b02e9b6c36c6.png)
