### ISSUE TITLE
Header Structure

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#330]
Notes: 
•	Please adjust all bold and strikethrough parts.
•	On “home" and pages with no clear heading for the “Content” please insert a hidden H1 (see below)
•	Please set after H1 Content a H2 (and not H3 or H4), see #243*

<strong>H1 Navigation and service area for the Department of the Environment, Transport, Energy and Communications</strong>
<strike>H2 Orientation in the website</strike>
<strike>H2 Title of page</strike>
H2 Language selection
H2 Service navigation
<strong><strike>H1 Department of the Environment, Transport, Energy and Communications</strike> ==> set this to H2 and hide it for screen readers</strike></strong>
H2 Search
H2 Breadcrumb <strong>navigation</strong> (if any)
H2 By topics
<strong>H2 Main navigation</strong>
<strike>H1 Main Title</strike>
<strike>H2 Search</strike>
<strong>H2 Sub navigation</strong>
<strong>H1 Content (hidden)</strong>
<strong>H2 Lorem ipsum title 1 (now it's H3 or H4*)</strong>
H2 Lorem ipsum title 2
H2 Lorem ipsum title 3
H2 Lorem ipsum title 4
H2 News
H2 Themes
…And so on…

**Comment by LeBenLeBen** [comment]
The overall headings hierarchy has been reviewed and improved in version 3.0.0.
