### ISSUE TITLE
Missing Slideshow

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#333]
Hi everybody,

we are just missing the slideshow in the new webguidelines. Maybe we didn't find it or ist this feature not implemented. 

Here is the link in the old webguidelines: 
http://preview.admin.ch/projekte/cdbund_1.1.1/basis/slideshow

Please send me your feedback as soon as possible. 

Kind regards, Lukas

**Comment by zufrieden** [comment]
Hi @LukasJaborsky 

I don't see any other element than the carrousel http://swiss.github.io/styleguide/content_modules_-_teaser.html#d-carousel

Kind regards
Marc

**Comment by LukasJaborsky** [comment]
Hi @zufrieden 

we don't look for the carrousel. You will the the difference when you click on a image in the old webguidelines. These are different requirements. 

http://preview.admin.ch/projekte/cdbund_1.1.1/basis/slideshow

**Comment by mbruellmann** [comment]
We have the photo gallery http://swiss.github.io/styleguide/content_modules_-_multimedia.html# - should do the trick

**Comment by LukasJaborsky** [comment]
Slideshow has another functionality and design than the photo gallery. This element is used 15 times. For example BBL is using this feature. Unfortunately we cant discard this feature.
