### ISSUE TITLE
Resetting of search value doesn't work

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#334]
Old ticket: https://github.com/swiss/styleguide/issues/306

Description: IE 10 renders an extra "X". Pressing the "X" does only delete the value, if you start typing right after you clicked the "X". If you enter something, then press "X" and then leave the field, the entered value is still going to be present

Browsers affected: IE 10 

Screenshot: 
![double_x](https://cloud.githubusercontent.com/assets/3909997/5630282/9da8adba-95bc-11e4-9ec6-96daeb81bcbc.PNG)

**Comment by zufrieden** [comment]
Thank you. We'll look into this one.

**Comment by tonifisler** [comment]
Is being worked on in PR #346
