### ISSUE TITLE
Feedback Release 2.4.0 - Images don't work

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#335]
The image references in 2.4.0 seem to be broken.

**Comment by zufrieden** [comment]
Which image ? All ?
Could you provide an URL ?

**Comment by mbruellmann** [comment]
no, not all.
Examples: 
http://swiss.github.io/styleguide/pages/detail.html#
http://swiss.github.io/styleguide/pages/homepage-global-nav.html

**Comment by zufrieden** [comment]
We use http://placehold.it/ to handle image generation. Maybe a problem with browser or proxy. We'll check.

![screenshot 2015-01-08 17 03 28](https://cloud.githubusercontent.com/assets/451236/5665392/5f0475e2-9758-11e4-8777-0b000245fd3c.png)

**Comment by tonifisler** [comment]
Definitely placehold.it having issues. Wait a few minutes and reload the page, you should be fine then.
