### ISSUE TITLE
Feedback 2.4.0 Links

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#336]
On an example page in Chrome and Firefox: When we click on a link, all links become violet (not just the one link we clicked on. 
![2 4 0 links clicked](https://cloud.githubusercontent.com/assets/7466385/5631116/2ffd2432-95c4-11e4-938e-ca0e5384b1e7.PNG)

**Comment by tonifisler** [comment]
This is absolutely normal, these are fake links pointing to `href="#"`. Duplicate issue of #269.
