### ISSUE TITLE
Form jumping away

### ISSUE THREAD

**Issue by webguidelines** [swiss/styleguide#338]
When using IE9 and clicking a check box or a radio button the forms page all the content is moving rightwards and the form isn't visible anymore. If the two scripts vendros.min.js and main.min.js are not included in the template the bug isn’t reproducible anymore.

**Comment by tonifisler** [comment]
This will surely be solved when we finally remove the plugin for radios and checkboxes. See #208.

**Comment by webguidelines** [comment]
Meanwhile I found out that it's not influenced by the scripts and it happens only if the checkboxes or radiobuttons are in one line.
