### ISSUE TITLE
Arrow-Icon jumps by clicking on it.

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#341]
Browser: all

Description:  Arrow-Icon and the text behind is jumping on the right side by clicking on it. 

Link: http://swiss.github.io/styleguide/content_modules_-_content_containers.html#c-dropdown-box

Screenshot: 
![screen shot 2015-01-15 at 12 41 27](https://cloud.githubusercontent.com/assets/3909997/5756797/dc100578-9cb3-11e4-9051-a8659de5758d.png)

**Comment by Yago** [comment]
@LukasJaborsky I can't recreate the bug, everything seems working fine. Can you be more explicit about your environment ?

![collapse](https://cloud.githubusercontent.com/assets/2025924/6002201/91aa288c-aaf1-11e4-9cd3-dced4eb344c3.gif)
