### ISSUE TITLE
Carousel iOS dots disappear after loading

### ISSUE THREAD

**Issue by tonifisler** [swiss/styleguide#344]
![ios simulator screen shot 19 jan 2015 10 33 26](https://cloud.githubusercontent.com/assets/1708450/5798333/b6b9b696-9fc6-11e4-8ce3-7266e6c7ec53.png)

**Comment by desobryc** [comment]
related to #367

**Comment by tonifisler** [comment]
Should be fixed when #381 is merged. Closing.

**Comment by desobryc** [comment]
Ok as far as I could see
