### ISSUE TITLE
Publications Preview: images are non-flush

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#348]
Browsers affected: all

Description: Images on publications preview are non-flush with the appropriate text.

Link: http://swiss.github.io/styleguide/content_modules_-_teaser.html#g-publications-preview

Screenshot: 
![publications_text](https://cloud.githubusercontent.com/assets/3909997/5834482/7a235234-a15e-11e4-9540-e378539439f7.png)

**Comment by Yago** [comment]
![capture d ecran 2015-02-02 a 15 19 39](https://cloud.githubusercontent.com/assets/2025924/6001920/ed2f4604-aaee-11e4-91f5-534d26684edd.png)
