### ISSUE TITLE
@font-face not working with Internet Explorer + HTTPS + Header Cache-Control / Pragma  

### ISSUE THREAD

**Issue by gamba** [swiss/styleguide#359]
Here a bizarre IE bug, so no change in *styleguide* is needed, nevertheless it would be good to mention it in the documentation. 

If IE loads a page over HTTPS with Cache-Control or Pragma headers set, then @font-face will not work (and make IE skip Frutiger and fall back to a default choice). 

Disabling cache control on fonts is the simplest way I found to let Frutiger load correctly on HTTPS apps: 

```bash
<FilesMatch "\.(eot|otf|woff|ttf)$">
   Header unset Cache-Control
   Header unset Pragma
</FilesMatch>
```

Here i found something on a m$ website: 
https://connect.microsoft.com/IE/feedbackdetail/view/992569/font-face-not-working-with-internet-explorer-and-http-header-pragma-no-cache

**Comment by tonifisler** [comment]
Thanks, we'll add this notice to the README file in the next update.

**Comment by dagnelies** [comment]
Btw, it's probably related to this bug report: https://connect.microsoft.com/IE/feedbackdetail/view/992569/font-face-not-working-with-internet-explorer-and-http-header-pragma-no-cache
