### ISSUE TITLE
Space is missing between form fields and submit button - smartphone portrait

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#363]
The submit button is to near to the last form field and a space is missing when looking at the page on smartphone portrait. 
![medienmitteilungen 20hochformat 20smartphone](https://cloud.githubusercontent.com/assets/7644740/6688074/f30d4d62-ccb0-11e4-9e69-2cbbed8f387a.png)

**Comment by tonifisler** [comment]
Can you provide a link to this page so we can have a look at the source of this issue?

**Comment by desobryc** [comment]
https://www.cmsp-r.admin.ch//gov/de/start/dokumentation/medienmitteilungen.html

**Comment by tonifisler** [comment]
The bug is not visible on iOS 8.1. Which device are you testing on?

(sorry for the delayed responses, I am abroad for the week)

![screen shot 2015-03-19 at 16 55 22](https://cloud.githubusercontent.com/assets/1708450/6735837/df2fe418-ce58-11e4-94ee-b34f1eaf906e.png)

**Comment by desobryc** [comment]
I'm testing on a Galaxy Alpha.

**Comment by tonifisler** [comment]
I fixed this issue by setting the clearfix properties to the `.form-group` element. 

You modified a lot of CSS and didn't use the Bootstrap classes here though. It should work as soon as you use the `.form-control` on the inputs. Please refer to http://swiss.github.io/styleguide/pages/forms.html and http://getbootstrap.com/css/#forms for more info.

**Comment by desobryc** [comment]
looks good om my samsung
