### ISSUE TITLE
A clic on a form field induces a zoom in, but submitting it don't induce a zoom out - Smartphones and tablets

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#365]
When clicking on a form field, smartphones and tables zoom in for a better usability, which is good. But when the user clicks on submit, it doesn't zoom out, which is not so usable as the user needs to zoom out himself in order to see the content of the page which is not displayed
![studiensuche 20rezoom](https://cloud.githubusercontent.com/assets/7644740/6688279/751749c4-ccb2-11e4-89b3-22524c91ff4a.PNG)

**Comment by tonifisler** [comment]
This is a default feature of Safari on iOS: if an input has a `font-size` set to a smaller size than `16px`, it will trigger this zoom. A workaround would be to increase the `font-size` for the form elements on mobile.

**Comment by desobryc** [comment]
SWG-81

**Comment by bit-pro-iew-eui** [comment]
Fehler nicht nnachvollziehbar
