### ISSUE TITLE
[2.5.2] Mobile view has a strange padding

### ISSUE THREAD

**Issue by ift-jsy** [swiss/styleguide#366]
Hello,

By migrating up to the version 2.5.2, I'v been trapped by a strange effect that happen only in mobile version: 
Screenshot of my portal:
![image](https://cloud.githubusercontent.com/assets/11071351/6753242/e357a370-cf14-11e4-801f-ea6f752eae24.png)
Screenshot of an example took from github
![image](https://cloud.githubusercontent.com/assets/11071351/6753272/0030cf44-cf15-11e4-8694-a73df7126c41.png)

There is a small gap which push the whole page to the left (and thus break the dropdown items). Have you any idea where/why comes this gap?

Thanks and Cheers,
Julien

**Comment by tonifisler** [comment]
Thanks for your report.

Can you provide a link to where this is happening? We'll have a look into it.

**Comment by ift-jsy** [comment]
Sorry it was my bad.There was a break line between the hyperlink and the span markup (for the icon) and surprisingly (at least for me :smirk:) it has bring the rendering down

**Wrong code**
```html
<a href="#" class="nav-mobile-menu dropdown-toggle" data-toggle="dropdown">
       <span class="icon icon--search"></span></a>
```
**Correct code**
```html
<a href="#" class="nav-mobile-menu dropdown-toggle" data-toggle="dropdown"><span class="icon icon--search"></span></a>
```
