### ISSUE TITLE
Focus isn't always displayed correctly

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#367]
The focus element (http://swiss.github.io/styleguide/content_modules_-_teaser.html#a-focus) is quite often buggy: double display, status icons (red points) or texts are missing, partial display on iphones. It possibly leads to a problem when reading videos on iphones (portait) when these are displayed in the focus teaser.

**Comment by desobryc** [comment]
![Uploading double focus.JPG…]()

**Comment by desobryc** [comment]
![double focus](https://cloud.githubusercontent.com/assets/7644740/7807682/c9bdb596-038d-11e5-9c2c-c18d6e92c6fd.JPG)

**Comment by desobryc** [comment]
![missing points](https://cloud.githubusercontent.com/assets/7644740/7807699/e05f7e06-038d-11e5-977a-d29d829f57c6.png)

**Comment by tonifisler** [comment]
There is some massive JS scripts handling the markup transformations between mobile and desktop versions of this element. We'll have to look into those and fix any issue we find.

**Comment by tonifisler** [comment]
This component is quite a mess. Should be refactored at some point.

**Comment by desobryc** [comment]
Ok for desktop on chrome, ie and firefox and for chrome and firefox on my samsung. 

Still need to test it for iphones
