### ISSUE TITLE
Disable "p" (80) keydown for print preview

### ISSUE THREAD

**Issue by gamba** [swiss/styleguide#369]
[styleguide/blob/master/assets/js/print.js](https://github.com/swiss/styleguide/blob/master/assets/js/print.js) (lines 98-104) adds a keydown binding for print preview. 

```
  $(document).bind('keydown', function(e) {
      var code = (e.keyCode ? e.keyCode : e.which);
      if (code == 80 && !$('body').hasClass('print-preview')) {
          $.printPreview.printPreview();
          return false;
      }
  });
```

Here we have issues when users write "p" in forms... because it will trigger the print preview.
We would like to use the complete/minimized main{.min}.js, without changes, but disable this print 
preview feature.

Whats the most elegant way to disable "p" keydown at all (or at least in forms) ?

**Comment by zufrieden** [comment]
Good point here. I think we can remove this feature in the next release.

**Comment by tonifisler** [comment]
:+1: for removing ;)

**Comment by gamba** [comment]
AFAYK, is there a way to properly unbind this keydown?

**Comment by tonifisler** [comment]
We removed this "feature" completely. It serves no real purpose and can is better being called from the button. e35a1fe2273c02ad39bb68405b2804b78de96aa7

**Comment by gamba** [comment]
:+1:
