### ISSUE TITLE
A page break before a table doesn't make sense wenn the table comes just after the page title

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#370]
![image](https://cloud.githubusercontent.com/assets/7644740/8473118/4d42b8ea-20a7-11e5-9af8-5e07a169c9b3.png)

**Comment by tonifisler** [comment]
Let's fix this with `page-break-inside` or a similar property. http://caniuse.com/#search=page-break

**Comment by desobryc** [comment]
looks good as far as I can see
