### ISSUE TITLE
p-Key in form-field shows print-view

### ISSUE THREAD

**Issue by maenujem** [swiss/styleguide#371]
When entering data containing a "p" (eg. apple) into a form-field (eg. http://swiss.github.io/styleguide/pages/forms.html ) the print-view suddenly appears and it is not possible to use the form field as expected.
When disabling either (?!) vendors.js or main.js the error does not occur.

PS: what are vendor.js and main.js for?

**Comment by tonifisler** [comment]
This is a major issue. We'll remove this feature completely, as it is non-essential.

**Comment by andreabettich** [comment]
+1 just found the same bug. Fires everywhere not only textfields.
Do you know when you will release 2.5.3?

**Comment by tonifisler** [comment]
Commented in e35a1fe2273c02ad39bb68405b2804b78de96aa7. Needs to be removed completely.

**Comment by tonifisler** [comment]
b44094378fcf2dc57735727fefa3fab136a4e59b
aba7b43a024e6024e85d418495ed9f092394fb78

**Comment by desobryc** [comment]
ok, looks good now.

**Comment by GS-VBS-Webteam** [comment]
Was tested in Chrome latest version, Firefox latest version und IE9. Now OK.
