### ISSUE TITLE
Tabs and Accordeon not showing sometimes when printing

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#372]
Der Tab-Inhalt wird gemäss CI/CD-Bund wie im Webbrowser dargestellt. Die Tabs, die nicht offen sind, werden nicht angezeigt. -> Muss im CI/CD Bund angepasst werden. (print.css)

**Comment by tonifisler** [comment]
Would these Bootstrap classes help? http://getbootstrap.com/css/#responsive-utilities-print

**Comment by desobryc** [comment]
Now tabs are being printed but the titles of the tabs are missing on the printstyle (documents, news, ..).
The word "tab" shouldn't be displayed, also see "contact tab" and "map tab" --> should be contact and map
The titles should be styled like titles: bigger, bold and not grey.
![image](https://cloud.githubusercontent.com/assets/7644740/9323825/d5b92a04-4584-11e5-9159-c175da93899d.png)
![image](https://cloud.githubusercontent.com/assets/7644740/9323768/4ffdac8c-4584-11e5-9321-42ee1464c54e.png)
![image](https://cloud.githubusercontent.com/assets/7644740/9323801/a4f726b4-4584-11e5-807b-2d211d5c2b37.png)

**Comment by tonifisler** [comment]
Fixed in 734f468
