### ISSUE TITLE
Left navigation is missing styles on mobile

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#373]
Die Leftnavigation ist in der Mobile-Ausprägung unschön gestyled. #bug

**Comment by tonifisler** [comment]
Thank you for your report. We don't understand exactly what you are talking about though. Could you provide us with more info? (browser version, screenshot of the issue and a URL)

Thank you

**Comment by tonifisler** [comment]
Thank you for your report @GS-VBS-Webteam. We don't understand exactly what you are talking about though. Could you provide us with more info? (browser version, screenshot of the issue and a URL)

Thank you

**Comment by GS-VBS-Webteam** [comment]
On mobile, the active page in the left navigation (where you are) is not shown correctly.

![cdbund_leftnav_style](https://cloud.githubusercontent.com/assets/9591815/9053882/68c440aa-3a7b-11e5-97e0-cb77f2362915.png)

**Comment by tonifisler** [comment]
Ok thank you, we'll look into that.

**Comment by GS-VBS-Webteam** [comment]
Steps to reproduce: 

 1. Open http://swiss.github.io/styleguide/pages/detail.html 
 2. Resize the browser window to the mobile viewport 
 3. Click on 'Sub-Navigation' to view the navigation 
 4. The navigation element 'Wine' is not styled properly 

 Browser-Versions: 

 - Safari 8.0.7 on OSX 10.10.4 Yosemite 
 - Firefox 39.0 on OSX 10.10.4 Yosemite 
 - Chrome 44.0.2403.125 on OSX 10.10.4 Yosemite

**Comment by desobryc** [comment]
looks good for my chrome, ie and firefox
![image](https://cloud.githubusercontent.com/assets/7644740/9323591/81387108-4582-11e5-8d13-28e75a552037.png)

**Comment by GS-VBS-Webteam** [comment]
Was tested in Chrome latest version and Safari iOS. Now OK.
