### ISSUE TITLE
Search field value on body click and  label

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#374]
Folgender JavaScript Teil muss noch angeschaut werden, darum wird der Get-Request nicht korrekt übertragen.

```js
$('body').on('click', function () { 
    $('#search-field').val(''); 
  }); 
```

Ebenso funktioniert das Label des Suchfelds in IE9 nicht. (Vgl. Auf dem IE9 wird der Stan-dardtext im Suchfeld ("Suche") nicht korrekt dargestellt. Ist auch schon in den Webguidelines so)

#bug

**Comment by tonifisler** [comment]
@GS-VBS-Webteam Could you please write all your bug reports in English? This is a way better way to communicate on this platform and we avoid misunderstanding that way. Thank you very much.

**Comment by desobryc** [comment]
looks good for me

**Comment by GS-VBS-Webteam** [comment]
The issue is fixed.
