### ISSUE TITLE
Infobox tiny image box height

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#375]
Bei der Bildgrösse Tiny image ist die Infobox (grauer Hintergrund) nicht so hoch wie die In-fobox selbst.
CD Bund: http://swiss.github.io/styleguide/content_modules_-_standard_elements.html#c-info-box

**Comment by tonifisler** [comment]
If I understand correctly, this is the issue you are talking about, right?

![screen shot 2015-07-08 at 10 13 02](https://cloud.githubusercontent.com/assets/1708450/8565901/1ad01e18-255a-11e5-9879-1ca2ccd100c7.png)

**Comment by GS-VBS-Webteam** [comment]
Yes, it is.

**Comment by mber-namics** [comment]
![umsetzung-namics-dev](https://cloud.githubusercontent.com/assets/7642132/9175557/9d6dddd8-3f86-11e5-84ed-3ebf67d3c26f.png)

**Comment by desobryc** [comment]
looks good
![image](https://cloud.githubusercontent.com/assets/7644740/9323344/f5725faa-457f-11e5-858e-e801feba51b3.png)

**Comment by GS-VBS-Webteam** [comment]
Was tested in  IE9, IE11, Firefox andChrome. Now OK.
