### ISSUE TITLE
Slideshow Label page X / Y is shifting from a place to another depending on space available

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#376]
Das Label "X of Y" soll laut CD-Bund links neben den Pfeilen sein. Sobald aber der Label Text zu lang wird (z.B. 100 of 120) verschiebt sich das Label unterhalb der Pfeile...
Mögliche Folge: X of Y Anzeige "springt" während dem Durchklicken durch die Slideshow (z.B. beim Wechsel von "9 of 15" nach "10 of 15")

**Comment by desobryc** [comment]
![vbs](https://cloud.githubusercontent.com/assets/7644740/9008106/2461ff82-3798-11e5-98e9-79d17f1451ad.png)

**Comment by desobryc** [comment]
http://swiss.github.io/styleguide/content_modules_-_teaser.html#d-slideshow

**Comment by desobryc** [comment]
@GS-VBS-Webteam I don't have a test case for this one, so you will have to look, thanks

**Comment by desobryc** [comment]
<img width="639" alt="2015-08-25_1606" src="https://cloud.githubusercontent.com/assets/7644740/9471251/c5fba710-4b4f-11e5-8940-a0b4fefed761.png">

Still not ok. The paging element is still shifting when big numbers of elements and pages are displayed

**Comment by tonifisler** [comment]
It is ok though. Now, the whole controls element (with the "< | >" arrows) is shifting when too big and not just the numbers. 

We have to let some room for a longer title:

<img width="571" alt="screen shot 2015-08-31 at 07 39 04" src="https://cloud.githubusercontent.com/assets/1708450/9572806/966f9f4c-4fb4-11e5-8037-83733853ab5d.png">

I've shifted the numbers closer to the controls now, so your 100/200 example is working.

We don't recommend having 99+ images though: that much images in a slideshow is a horrible idea (even 20 seems too much). Nobody wants to browse that much images in a slideshow and it would just kill performances when loading the page.
