### ISSUE TITLE
Treecrumb

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#377]
![treecrumb](https://cloud.githubusercontent.com/assets/7466385/9106480/dd758458-3c20-11e5-92d1-e9f694138d4b.png)
The treecrumb should start with "Federal Council", not with "Federal Administration".

**Comment by desobryc** [comment]
SWG-83

**Comment by LeBenLeBen** [comment]
Fixed by a592cd580acfa6a698f5ad5cf6d9e46700a5cb96
