### ISSUE TITLE
Correction in the description of "Language Selection via a Link List"

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#378]
http://swiss.github.io/styleguide/navigation_modules_-_header.html#d-lang-navigation-list
It should read "The following rules apply for the language navigation:
German, French and Italian (not: English) are mandatory. Therefore the abbreviations DE, FR and IT are always and on each page visible..."

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-82

**Comment by LeBenLeBen** [comment]
Fixed in 3.0.0
