### ISSUE TITLE
Add favico documentation to the "CD Elements" section

### ISSUE THREAD

**Issue by benoitpointet** [swiss/styleguide#380]
Add favico documentation to the "CD Elements" section, to help implementors not forget it.
Cf https://www.eda.admin.ch/eda/de/home.html

**Comment by desobryc** [comment]
ok
![image](https://cloud.githubusercontent.com/assets/7644740/9323357/38080234-4580-11e5-8954-49e0d693922b.png)

**Comment by benoitpointet** [comment]
great!
