### ISSUE TITLE
Image format 

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#383]
It should be possible to wrap text around Images up to 258 width (not just up to 180 as in the current version) 
http://swiss.github.io/styleguide/base_layout_-_general.html#c-image-format 
(DETEC)

**Comment by tonifisler** [comment]
The image can be any size, you just add to add the `.pull-left` or `.pull-right` class to the `<figure>` and you can then have text wrapping around it. See: http://swiss.github.io/styleguide/content_modules_-_standard_elements.html#b-image-text

**Comment by mbruellmann** [comment]
Hi Tony. Sure. The problem is that the webpublishers who work with a CMS  cannot do that. Never mind. We are collecting issues here which should go into a release 3. If and when release 3.0 is  going to happen we do not know yet.

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-86

**Comment by desobryc** [comment]
This is possible and is only a question of implementation, so I close it.
