### ISSUE TITLE
Print doesn't work correctly

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#387]
### Expected behavior

A page is displayed in print preview when:

1. P key is pressed
2. keys Cmd + P are pressed (OSX) or Ctrl + P (Windows)
3. Print icon is selected on the page
4. Print is selected in the browser menu
  - Firefox on OSX "File> Print"
  - Chrome on OSX "Burger navigation> Print"
  - IE9 on Windows 7 "cogwheel icon (Menu)> Print> Print Preview"

### Current behavior

1. system works correctly
2. system works correctly
3. No action of the system results of a click on the print icon. The print view is displayed.
4. The print template is not used by the printing process. Elements of the page including the navigation are displayed unstructured.

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-84

**Comment by desobryc** [comment]
This cannot be solved as the browser standard behavior cannot be influenced (within reasonable costs).
