### ISSUE TITLE
H2/H3 Titel have the same size by a certain zoom level

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#388]
Bug in the CD Bund Responsive Design. Can be reproduced on http://swiss.github.io/styleguide/pages/detail.html by shrinking the browser window.

  specification:
  CMS VBS_RfC_CR020_Titel H2 H3

  Test environment:
  Author + Publish

  browser:
  Firefox 39.0

  Url:
http://test-publish-internet-vbs.namics.com/content/baqs-internet/de/ruag-testbereich/test-1.html

  Test Steps:
  1. Insert a component title. Define the title with H2.
  2. Insert a component title. Define the title with H3.
  3. representation on Author and Publish environment check: Change zoom level of the browser (zoom in).

  Current result:
  From the zoom level 200%, the two items are equal.

  Expected Result:
  For all zoom levels, the heading H2 is greater than H3.

![h2h3nok_zoom_200](https://cloud.githubusercontent.com/assets/9591815/9654952/585c66f0-522e-11e5-8d6c-37eb60cc91a9.PNG)
![h2h3ok_zoom_standard](https://cloud.githubusercontent.com/assets/9591815/9654956/5cf042e0-522e-11e5-9eb7-3f5fe1b30a1b.PNG)
![viewport-desktop](https://cloud.githubusercontent.com/assets/9591815/9654960/60ccc910-522e-11e5-9eac-f44abf8464cf.png)
![viewport-tablet-hochformat](https://cloud.githubusercontent.com/assets/9591815/9654963/67dfeeee-522e-11e5-8c53-0020315532ce.png)

**Comment by tonifisler** [comment]
Thanks for this very well explained report. We'll have to update this line:

https://github.com/swiss/styleguide/blob/master/assets/sass/layout/titles.scss#L66

And generally review all the responsive typography rules.

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-85

**Comment by LeBenLeBen** [comment]
This issue has been addressed in version 3.0.0.
