### ISSUE TITLE
Add 4-columns-wide focus 

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#394]
Add 4-columns-wide focus as used on www.admin.ch

![4-columns-focus](https://cloud.githubusercontent.com/assets/7466385/9876594/8e94ccde-5bb7-11e5-9c2c-15a00d8e127b.png)

to  http://swiss.github.io/styleguide/content_modules_-_teaser.html#a-focus

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-92

**Comment by bit-pro-iew-eui** [comment]
@mbruellmann Matthias, can you provide the example of www.admin.ch with a 4-columns-wide focus? I didn't find the one you mean

**Comment by bit-pro-iew-eui** [comment]
The actual link of the teaser focus is https://swiss.github.io/styleguide/de/teaser.html#05-teaser-01-focus, the expected implementation is that additionally a teaser-focus is implemented where the links appear horizontally on the right as in admin.ch, the whole widget should be content wide.

![image](https://user-images.githubusercontent.com/7510842/27914883-c79c96aa-6264-11e7-86b0-7bb416db7581.png)
