### ISSUE TITLE
Add teaser for social media 

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#395]
Add a teaser for social media (Twitter, Facebook etc.) on the basis of Twitter teaser on www.admin.ch

![social_media_teaser](https://cloud.githubusercontent.com/assets/7466385/9876648/0432c860-5bb8-11e5-876f-22d7e31bb694.png)

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-94

**Comment by q-src** [comment]
@mbruellmann On admin.ch all pictures in the twitter stream are hidden. Is this intended or shall the webguidelines display pictures?

**Comment by mbruellmann** [comment]
Both actually. Default is with pictures. On admin.ch we have a problem right now with that. IE does not display any pictures; Firefox produces an error. @q-src @ @
