### ISSUE TITLE
Define style of <hr>

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#397]
In CSS define the style of the `<hr>`-Element

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-96

**Comment by LeBenLeBen** [comment]
The `<hr>` element already has some styling.

![capture d ecran 2015-12-16 a 13 08 02](https://cloud.githubusercontent.com/assets/793344/11840435/2ddc985e-a3f6-11e5-8454-aff8a4ee7b55.png)
