### ISSUE TITLE
Form wizard visualization wraps to new line, if last item is active .nav-process

### ISSUE THREAD

**Issue by RolandStuder** [swiss/styleguide#400]
The indicator to show multiple steps in forms wraps elements to a new line, if the first or last items are set to active. It works fine if one of the middle steps are set to active.

![Example](https://cloud.githubusercontent.com/assets/194364/10163230/c00ac37c-66b1-11e5-8a8a-485c172cb23b.png)

This concerns this component:
http://swiss.github.io/styleguide/navigation_modules_-_content_navigation.html#c-process-navigation

html

    <nav class="nav-process">
      <ul>
        <li>
          <a href="#">Step 1</a>
        </li>
        <li>
          <a href="#">Step 2</a>
        </li>
        <li class="disabled">
          <a href="#">Step 3</a>
        </li>
        <li class="active">
          <a href="#">Step 4</a>
        </li>
      </ul>
    </nav>

This is due to the following css:

    .nav-process li a {
        display: block;
        height: 6px;
        width: 24.2%;
        float: left;
        background: #D5D5D5;
        margin: 0 .5%;
        color: #000;
        text-align: center;
        font-size: 13px;
        line-height: 35px;
        position: relative;
    }

Our current workaround is to reduce the width to 24%, which looks ok.

A more robust component that would adjust widths for different numbers of steps would be preferable anyway. But at least the widths should be adjusted that it actually works with four steps. Also it would be good to update the documentation and show what selector is doing the work, so overrides for different widths can be applied easily. 

Only tested this on Google Chrome OS X Version 45.0.2454.99 (64-bit)

**Comment by RolandStuder** [comment]
I made a pull request that resolves the issue and adds the flexbility to use the component for 2-10 steps. https://github.com/swiss/styleguide/pull/417 Sorry for the unnecessary commits, not so good with git yet :-)

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-99

**Comment by LeBenLeBen** [comment]
Hi Roland,

First, thanks for your contribution. The issue you mentioned has been addressed in version 3.0.0.

Concerning your feature with more steps, we can sadly not accept your pull-request as is. This component has many issues and modifying it like this would make it even more complicate. We should refactor it to support multiline labels, be responsive and has a variable number of steps. This can be done obviously but the Chancellery decided to not include it in version 3.0.0.

The best way for you to have this being taken into consideration for a further version is to open a new issue explaining your use case for this change and how you would like it to behave with details about how many steps and why.

**Comment by mbruellmann** [comment]
The guidelines provide a design solution for the step-by-step-navigation, not a functional one. The actual programming depends on the specific shop and has to be done by the individual project.
