### ISSUE TITLE
Photo Gallerie Lightbox Browsing

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#402]
When a user clics on a picture of the Photo Gallery element, the picture appears bigger in a Lightbox. Some elements appears too in the lightbox : title, descrition, copyright, ...
It is not possible to browse the gallery with arrows, in both directions (left and right). This function (Photo Gallery browsing) should be added to the element as it is expected from users. 

![photogallerielightboxbrowsing](https://cloud.githubusercontent.com/assets/9591815/10193475/b160607a-6783-11e5-9095-88df05690929.png)

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-100

**Comment by desobryc** [comment]
The arrows are there, but only appear when you click on the picture. This will be fixed.

**Comment by LeBenLeBen** [comment]
Note: the navigation is available on the [Slideshow](http://swiss.github.io/styleguide/content_modules_-_teaser.html#d-slideshow) component but not on the [Lightbox](http://swiss.github.io/styleguide/content_modules_-_multimedia.html#c-lightbox) component.

The lightbox component is mentioning "The user can then browse through various images using the arrow icons in the "lightbox" or the arrow keys on the keyboard." in the description but this doesn’t seems to be a supported feature. We should probably consider removing this sentence if we don’t want to invest time on it now.

**Comment by desobryc** [comment]
Ok, can you please remove it?

**Comment by LeBenLeBen** [comment]
Sure!

**Comment by LeBenLeBen** [comment]
@desobryc Can we consider this as resolved?

**Comment by desobryc** [comment]
Yes we can, thanks
Le 16 déc. 2015 07:05, "Benoît Burgener" <notifications@github.com> a
écrit :

**Comment by GS-VBS-Webteam** [comment]
I'd like to know if the issue with the lightbox will be fixed in the release 3.0.

**Comment by GS-VBS-Webteam** [comment]
Quand on ouvre une visionneuse, le site Internet en arrière-plan est obscurci. La visionneuse est constituée du titre, de la vue d’image en grand format et d’une légende. **A l’aide des icônes de flèches dans la visionneuse ou des touches de flèches du clavier, l’utilisateur peut faire défiler les différentes images. **La visionneuse peut être fermée en cliquant sur l’arrière-plan, sur le lien de fermeture ou encore avec la touche ECHAP.

Wird eine Lightbox geöffnet, wird die Webseite im Hintergrund abgedunkelt. Die Lightbox besteht aus dem Titel, der Grossansicht eines Bildes und einer Legende. **Mit Pfeil-Icons in der Lightbox oder mit den Pfeil-Tasten auf der Tastatur kann der Anwender zwischen verschiedenen Bildern blättern.** Die Lightbox kann durch einen Klick auf den Hintergrund, dem Schliessen-Link oder mit der ESC-Taste geschlossen werden.

When a "lightbox" is opened, the website in the background is darkened. The "lightbox" comprises the title, the full view of the image, and its caption. The "lightbox" can be closed by clicking on the background, and by using the close command or the Esc key.

The sentence " "The user can then browse through various images using the arrow icons in the "lightbox" or the arrow keys on the keyboard." in the description but this doesn’t seems to be a supported feature. " was removed only in the English version. It is still there in the french and german version.
