### ISSUE TITLE
Faceted-Navigation Result Page

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#404]
The Styling of "Seite 1 von 2" on a Tablet (iOS Safari / iPad) in Portrait format is not correct.

![img_0081](https://cloud.githubusercontent.com/assets/9591815/10306140/40fb1cac-6c25-11e5-9e26-4ebf4572dfec.png)

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-101

**Comment by GS-VBS-Webteam** [comment]
Kann dieses Issue im neuen Release (Milestone) übernommen werden ?

**Comment by mbruellmann** [comment]
It looks like the same issue described in #476
