### ISSUE TITLE
Responsive View - Galerie - The Lightbox cannot be closed

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#406]
The Lightbox cannot be closed in a mobile device, because the black layer is over the picture. 

![img_0076](https://cloud.githubusercontent.com/assets/9591815/10306204/a0c46eae-6c25-11e5-8467-0acd11b1a0cb.PNG)

![reproduction-cd-bund](https://cloud.githubusercontent.com/assets/9591815/10306208/a6240788-6c25-11e5-9510-f759b95ed246.png)

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-102

**Comment by LeBenLeBen** [comment]
This issue has been addressed in #439 and will be part of version 3.0.0.
