### ISSUE TITLE
The Alerts appears differently in browsers

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#407]
The Alerts appears differently in IE, Firefox and Chrome:
The exclamation mark is black only in IE.
Reference: http://swiss.github.io/styleguide/content_modules_-_widgets.html#a-alerts

Chrome

![chrome](https://cloud.githubusercontent.com/assets/9591815/10306239/dac16d50-6c25-11e5-8f55-55c8c7bc6823.PNG)

Firefox

![firefox](https://cloud.githubusercontent.com/assets/9591815/10306242/e311255e-6c25-11e5-8ebe-a7f2d73b2869.PNG)

IE

![ie](https://cloud.githubusercontent.com/assets/9591815/10306249/e82821be-6c25-11e5-85cb-9a26e93fd90c.PNG)

**Comment by tonifisler** [comment]
The font icons should be replaced with a more future-friendly component.

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-93

**Comment by desobryc** [comment]
This will be fixed with 3.0

**Comment by GS-VBS-Webteam** [comment]
No milestone is mentioned. Was ist fixed with 3.0 ?

**Comment by LeBenLeBen** [comment]
Both missing icons and size issue were fixed in 3.0.0

**Comment by chlab** [comment]
There still seems to be an issue with this.
This is a screenshot of [the styleguide](https://swiss.github.io/styleguide/en/widgets.html#03-widgets-01-alerts) in IE 10.0.9xx:

![screen shot 2016-11-30 at 11 50 16](https://cloud.githubusercontent.com/assets/1931446/20749697/ae0742f2-b6f3-11e6-85a4-62c58ec11b37.png)

There only seems to be a problem with `.alert-warning` exclamation mark icon.
