### ISSUE TITLE
Picture in the lightbox of the picture gallery not centered. 

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#412]
The picture in the lightbox of the picture gallery is not centered. 
![gallery-lightbox-imagenotcentered2009_47_44](https://cloud.githubusercontent.com/assets/9591815/10660470/8b726414-78a7-11e5-88f2-cf5cff657a92.png)

**Comment by tonifisler** [comment]
First (as a note for us), the `.modal` itself should have a `z-index` of at least 1050, to fix the overlay recovering it.

To center the image, you can simply add the Bootstrap class `.center-block` to the image itself.

Should you decide this behaviour to be the default one, we can gladly implement it.

**Comment by tonifisler** [comment]
Reer to #406 for the z-index issue.

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-104

**Comment by GS-VBS-Webteam** [comment]
Kann man das Issue im neuen Release (Milestone) übernehmen ?
