### ISSUE TITLE
Width of the first column of the form too narrow

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#413]
The column width of the first column of the form could be increased in order to get  more space for the descriptions of the fields. 
![spaltenbreite_forms](https://cloud.githubusercontent.com/assets/9591815/10663134/46e6952e-78b9-11e5-9bb6-cf2cd19aab4d.png)
 
![spaltenbreite_forms2](https://cloud.githubusercontent.com/assets/9591815/10663139/53ae2c4a-78b9-11e5-842a-469ad45f2a33.png)

**Comment by tonifisler** [comment]
When the layout is so cramped up between 2 sidebars, a form should never look like this. This is a design issue.

The solution is to simply move the labels above the input fields. This brings also a greater user experience and therefore accessibility.

![screen shot 2015-10-27 at 17 53 35](https://cloud.githubusercontent.com/assets/1708450/10765598/d63f6570-7cd3-11e5-9cd9-98b69dee45ac.png)

**Comment by RolandStuder** [comment]
## control the width of the label and the input

Actually this behaviour is already fully under your control. You control the width of the label and the form input with your class names on the inputs

For example:

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label" id="email">Email</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="Email" aria-labelledby="email">
      </div>
    </div>

The classes "col-sm-2" and "col-sm-10" control the width within the 12-column grid. So if you want more space for you labels, you just increase the class on the label, to something like "col-sm-4" and you reduce the div width with "col-sm-8"

## Option of earlier breakpoint

Also you can choose to show the label above the input field at an earlier breakpoint if you use "col-md-4" and "col-md-8". For the full reference of how the grid works have a look directly at the bootstrap grid documentation: http://getbootstrap.com/css/#grid

## Option of top labels

If you do not want the labels to be at the left at any viewport, then just remove the "col-…" classes.

So I would not consider this a bug, it's just how the grid systems works. With this markup no other result can be expected. On only could consider setting other defaults and examples in the documentation.

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-105

**Comment by desobryc** [comment]
The Styleguide is based on the bootstrap grid, which is adaptable. If you need more space, you just need to adapt the width of the first column. More instructions can be found here: http://getbootstrap.com/css/#grid
