### ISSUE TITLE
Some icons are missing or do not display properly

### ISSUE THREAD

**Issue by LeBenLeBen** [swiss/styleguide#421]
On [this page](http://swiss.github.io/styleguide/base_layout_-_general.html#e-icons) some icons are missing from the list. Notebook is not displaying in Chrome OS X (at least). Print icon is not displaying on Android Chrome nor iOS 9 Safari.

![capture d ecran 2015-11-24 a 14 55 38](https://cloud.githubusercontent.com/assets/793344/11368700/7d71a964-92bb-11e5-969d-817a5aa7bd0d.png)

![img_3007](https://cloud.githubusercontent.com/assets/793344/11368710/8a97b48a-92bb-11e5-9a09-1ec4cbd473e8.jpg)

**Comment by LeBenLeBen** [comment]
The print icon seems to be voluntarily hidden on small screen. I’m not sure it makes sense in all cases, like on [this example](http://swiss.github.io/styleguide/base_layout_-_forms_elements.html#f-buttons) where the button stay visible but not the icon.

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-108

**Comment by LeBenLeBen** [comment]
Notebook icon is fixed as of version 3.0

**Comment by LeBenLeBen** [comment]
Addressed in #441
