### ISSUE TITLE
The checkboxes disappear when zooming (Chrome v47 OSX)

### ISSUE THREAD

**Issue by pfritsch** [swiss/styleguide#448]
By zooming in or out, the checkboxes disappear. Ex (zoom 125%):
![hidden_checkboxes](https://cloud.githubusercontent.com/assets/2621526/12620129/3e0f180a-c51b-11e5-9223-d3d71fb094d8.png)

It's probably due the replacement of standard components with an svg-sprite background on a pseudo element (before), the background position seems to be misinterpreted.

**Comment by LeBenLeBen** [comment]
This issue has been addressed in the version 3, checkboxes and radios are back to their browser default state.
