### ISSUE TITLE
Code appears in print version for accordeon elements

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#450]
There is an issue in the print version of a webpage. When there is an element "accordion", the number of the element appears next to the title.

> Sportwissenschaft und Medizin (#collapse_accordion_0) 
> Monitoring und Evaluation (#collapse_accordion_1) 
> Sportpädagogik (#collapse_accordion_2) 
> Sportmanagement (#collapse_accordion_3) 
> Lernmedien (#collapse_accordion_4) 
> Sportanlagenbau (#collapse_accordion_5) 

![accordeon-webpage](https://cloud.githubusercontent.com/assets/9591815/12715011/1d8bec46-c8d8-11e5-8e1d-40f153c7e43e.jpg)
Webpage
![accordeon-print](https://cloud.githubusercontent.com/assets/9591815/12715014/1fa60d5e-c8d8-11e5-9a54-594032346096.jpg)
Print version

There is a second issue. The content of the element "accordion" is printed only when is it opened. It means that the user has to open the element he wants to have on the printed document. It would be easier when all contents elements of the page are printed

**Comment by GS-VBS-Webteam** [comment]
Kann man das Issue im neuen Release (Milestone) übernehmen ?

**Comment by bit-pro-iew-eui** [comment]
Please review and estimate @topaxi

**Comment by GS-VBS-Webteam** [comment]
Will be the two issues solved ?
1. the number of the element appearing next to the title
2. all the content elements must be present in the print version
