### ISSUE TITLE
Issue in IE11 with newsteaser

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#451]
![viewport-tablet](https://cloud.githubusercontent.com/assets/9591815/12715349/249861c0-c8da-11e5-84cf-267a19c78aed.png)
Issue in IE11 with newsteaser

**Comment by desobryc** [comment]
I'm sorry but I can't reproduce this bug, can you provide more information on how to get the same screen? I used IE 11 and looked at following page: http://swiss.github.io/styleguide/content_modules_-_teaser.html#b-news and I tried to reduce the window but without results. Thanks!

**Comment by GS-VBS-Webteam** [comment]
Die Tablet-View auf IE11 greift nicht.

**Comment by bit-pro-iew-eui** [comment]
@GS-VBS-Webteam can you please confirm, which version of the Web Guidelines are you using in your CMS?

**Comment by GS-VBS-Webteam** [comment]
Wir haben die Version 2.6 umgesetzt. Wir planen die Umsetzung der zukünftigen Version im Herbst.

**Comment by bit-pro-iew-eui** [comment]
Der Fehler kann nicht reproduziert werden
