### ISSUE TITLE
Form: Checkbox: Unselectable individual CheckBoxes

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#452]
There is an issue with small containers and long labelling texts. In this case, the checkbox cannot be selected. 
![formular_checkbox](https://cloud.githubusercontent.com/assets/9591815/12715475/da12eafc-c8da-11e5-8f56-480244ef5c88.png)

**Comment by LeBenLeBen** [comment]
What do you mean by small containers? Do you have an example of context in which it doesn’t work? A bunch of code would be perfect.

**Comment by GS-VBS-Webteam** [comment]
Video demonstrating the issue : 

http://screencast.com/t/HDHSUeT6e7Qt

Code-Extract:

<div class="form-group">
          <label class="col-sm-2 control-label" id="check-group-2">Terms</label>
          <div class="col-sm-10">
            <label class="checkbox-inline">
              <div class="checkbox checkbox--left">
                <input id="checkboxform3" type="checkbox" aria-labelledby="check-group-2 checkbox-label-3">
                <label id="checkbox-label-3" for="checkboxform3">Anreise per Zug</label>
              </div>
            </label>
            <label class="checkbox-inline">
              <div class="checkbox checkbox--left">
                <input id="checkboxform4" type="checkbox" aria-labelledby="check-group-2 checkbox-label-4">
                <label id="checkbox-label-4" for="checkboxform4">Anreise per Auto</label>
              </div>
            </label>
  <label class="checkbox-inline">
              <div class="checkbox checkbox--left">
                <input id="checkboxform5" type="checkbox" aria-labelledby="check-group-2 checkbox-label-5">
                <label id="checkbox-label-5" for="checkboxform5">Anreise mit Shuttlebus</label>
              </div>
            </label>
          </div>
        </div>

**Comment by GS-VBS-Webteam** [comment]
Das Ticket kann aus unserer Sicht geschlossen werden.

**Comment by bit-pro-iew-eui** [comment]
Closing issue due to the previous comment of @GS-VBS-Webteam
