### ISSUE TITLE
Not possible to use multiple slide shows or photo galleries on the same page

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#453]
It is not possible to use multiple slide shows or photo galleries on the same page. The JS-actions are then always applied to both stuff.
This is due to an incorrect implementation of the part of CI / CD Bund:
The ID must be unique on the <div class = "Carousel Carousel Slideshow" ..>, like any ID.
 Same for the navigation elements (bullets and right / left).

**Comment by LeBenLeBen** [comment]
It is actually possible but you have to change this ID. As you said an ID is unique so you should use a different one for each slideshow on your page. You are free to change it as they are not used to make the slideshow work. However you should ensure that your navigation si targeting the correct slideshow ID in their `href` attributes.
