### ISSUE TITLE
Scrollbar in Newsteaser

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#454]
There is always a scrollbar in the Newsteaser, even if there is enough room for the content. 
http://swiss.github.io/styleguide/pages/homepage-global-nav.html

**Comment by LeBenLeBen** [comment]
This is probably caused by the `overflow` property being set to `scroll` instead of `auto`.

**Comment by GS-VBS-Webteam** [comment]
Thank you for fixing this issue.
