### ISSUE TITLE
Image gallery: display of the previous - next functionality of the single view mode should be correctly displayed when using IE (11)

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#475]
![grey line photo single mode](https://cloud.githubusercontent.com/assets/7644740/13104285/75abb52e-d55c-11e5-8d13-7da183546f7a.PNG)

**Comment by bit-pro-iew-eui** [comment]
Hi @desobryc, can you explain what is not working exactly? Or what is the expected behaviour?

**Comment by desobryc** [comment]
The expected behaviour is that the grey line continues below previous and next und doesn't stop before previous like on the picture.

**Comment by mbruellmann** [comment]
We close this one. We have asssigned with #528
