### ISSUE TITLE
Image gallery: display of the object x from y of the overview mode should be correctly displayed when using IE (11) on mobile

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#476]
![photo gallery overview mobile](https://cloud.githubusercontent.com/assets/7644740/13104324/c09b37a8-d55c-11e5-91f2-7ab7920719f2.PNG)

**Comment by bit-pro-iew-eui** [comment]
Hi @desobryc, can you explain what is not working exactly? Or what is the expected behaviour?

**Comment by bit-pro-iew-eui** [comment]
Hi @desobryc, can you explain what is not working exactly? Or what is the expected behaviour?

**Comment by desobryc** [comment]
Yes, object 2 of 3 and Previous should be aligned.

**Comment by janissbinder** [comment]
this issue was fixed with #404

**Comment by bit-pro-iew-eui** [comment]
Fixed
