### ISSUE TITLE
Starter Package Code for Webdesign Bund

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#477]
As a webguideline users, I want to download and install a basic starter kit to create websites according to the Webdesign Bund. The package contains an index.html and example pages, a readme-file and the minified ressources.
The index files is a page of the type "Homepage with Global navigation".
The additional files are of the type
1. Homepage with global navigation
2. Detail page
3. Search Result page
4. Form page
5. Publication page

The code has no or only dummy content.

**Comment by bit-pro-iew-eui** [comment]
This issue can be implemented at the same time as #496, #515, #488

**Comment by mbruellmann** [comment]
to be discussed in the Webforum Bund. Probably we also should have a wordpress theme based on the webdesign bund.

**Comment by gillerr** [comment]
won't fix
