### ISSUE TITLE
There is no logo on print preview

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#480]
On the print preview, no logo of the swiss administration is displayed.

**Comment by bit-pro-iew-eui** [comment]
@desobryc can you please specify where? There's a logo in print preview i.e. in the homepage:

## Print preview screenshot on IE11
![image](https://cloud.githubusercontent.com/assets/7510842/22787093/625e9ede-eedb-11e6-9a26-88ce7f701a61.png)

**Comment by desobryc** [comment]
You have to use the print icon of the webguidelines 

![icon missing webguidelines](https://cloud.githubusercontent.com/assets/7644740/24896348/c6b4a8b8-1e94-11e7-985e-e5d78e956b96.PNG)
![print icon webguidelines](https://cloud.githubusercontent.com/assets/7644740/24896347/c6b49c06-1e94-11e7-8c06-fb626d54113c.PNG)
