### ISSUE TITLE
Add new top-link and end of page link component

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#481]

**Comment by bit-pro-iew-eui** [comment]
The top-link and end-of-page link components are in the guideline here:
https://swiss.github.io/styleguide/en/typography.html#04-typography-10-end-page-link
 and here: https://swiss.github.io/styleguide/en/typography.html#04-typography-09-top-link

What do you mean with "new" top-link and end-of-page link? How do they should look like anew?

**Comment by desobryc** [comment]
I can't remember anymore, so I think this issue can be closed.
