### ISSUE TITLE
Left menu (secondary navigation) disappears on some specific page widths. 

### ISSUE THREAD

**Issue by suterma** [swiss/styleguide#489]
There are some specific browser widths that cause the left menu to disappear, but the mobile-friendly stack menu does not yet kick in.

I have encountered this on Chrome and Firefox, using the example pages, as well as the productive pages, for example at https://www.admin.ch/gov/de/start/bundesrat/mitglieder-des-bundesrates.html.

The specfic broswer witdths are
- below 785px the left menu disappears
- below 768px the mobile-friendly menu kicks in

Please have a look at it, I feel this is a bug.

**Comment by LeBenLeBen** [comment]
Are you sure about the 785px? Nothing change in the page at this resolution for me. However I confirm there is an issue at exactly 768px, at which the treecrumb and the breadcrumb disappear.

Maybe some zoom or text size settings in your browser affect this?

**Comment by suterma** [comment]
Hi Benoit,

the 785px was the upper boundary of the anomaly, detected on a Window7 
machine. This time with Ubuntu and Chrome, the anomaly had the upper end 
at 781px, as shown in the screen shot. This is a default installation of 
Ubuntu Version 14.04 LTS.

It's exact behaviour may probably be dependent on OS and Browser. 
However, I have always been able to observe it at some width in that range.

Best Regards, Marcel

**Comment by suterma** [comment]
The attached screenshots show the problem on a current Firefox (45.0.2) on a Windows 7 system. The sizes are set to the upper and lower limit of the screen, where the problem occur. Outside these boundaries, either version of the menu is shown, inside the boundaries, no menu is show at all. See the rulers to get an indication of the screen width.

**Comment by suterma** [comment]
The attached screenshots show the problem on a current Firefox (45.0.2) on a Windows 7 system. The sizes are set to the upper and lower limit of the screen, where the problem occur. Outside these boundaries, either version of the menu is shown, inside the boundaries, no menu is show at all. See the rulers to get an indication of the screen width.

**Comment by suterma** [comment]
The attached screenshots show the problem on a current Firefox (45.0.2) on a Windows 7 system. The sizes are set to the upper and lower limit of the screen, where the problem occur. Outside these boundaries, either version of the menu is shown, inside the boundaries, no menu is show at all. See the rulers to get an indication of the screen width.

![www_admin_ch_gov_de_start_bundesrat_mitglieder-des-bundesrates_html](https://cloud.githubusercontent.com/assets/11473920/14846137/6c6fba54-0c62-11e6-97f5-5f3f5fd82a8f.png)
![www_admin_ch_gov_de_start_bundesrat_mitglieder-des-bundesrates_html2](https://cloud.githubusercontent.com/assets/11473920/14846142/703d76a8-0c62-11e6-86dd-54a6c190fbcb.png)

**Comment by LeBenLeBen** [comment]
Ok, I was not able to reproduce the problem on OS X but I think I have an idea why it happens. There’s [some JavaScript code](https://github.com/swiss/styleguide/blob/master/src/assets/js/subnavigation.js#L32) modifying this part depending on the screen size. It’s based on the window width and there might be a difference with CSS media queries calculation. I highly think the mismatch comes from the scrollbar width not being taken into account, being the 17px of difference between two calculation.

We should probably ditch `$(window).width()` in favor of `matchMedia` here to ensure it is strictly the same as stylesheets rules.
