### ISSUE TITLE
margin top space to big for lists

### ISSUE THREAD

**Issue by desobryc** [swiss/styleguide#492]
ul elements present a readability problem because titles and bullets are too wide apart from each other. Removing the top-margin from 1.5em could be the solution.
![ul](https://cloud.githubusercontent.com/assets/7644740/16407142/6b6eef86-3d12-11e6-9855-82649bef4587.png)

**Comment by mbruellmann** [comment]
Abstand zwischen Zwischenüberschrift und erstem Listenelement soll gleich gross sein wie Abstand zwischen Listenelementen. 
Abstand zwischen letztem Listenelement und nächstem Zwischentitel ist okay.
