### ISSUE TITLE
Displacement of content when using LightBox

### ISSUE THREAD

**Issue by suterma** [swiss/styleguide#495]
When using the Lightbox-Example in https://swiss.github.io/styleguide/de/multimedia.html#06-multimedia-03-lightbox, as soon as the modal dialog is shown, the underlying page gets displaced by visually notable amount of pixels. This seems to be caused by this additional element style, which is added to the document body on showing the modal dialog:

`<body style="padding-right: 17px;" class="modal-open">`

The problem is probably somewhere in the javascript code that handles the modal dialog fades.

**Comment by bit-pro-iew-eui** [comment]
@suterma I can't reproduce the issue. Can you provide which steps should be followed, browser name, browser version?

**Comment by suterma** [comment]
This issue is still valid today. I have tested on a recent Chrome Browser Version 59.0.3071.104 (Official Build) (64-bit) on Ubuntu 14.04. See attached Screenshots. It occurs on all window widths from small to very large. Attached you find 2 images, one before loading the modal dialog, one with the dialog show. Notice the slightly left-shifted content in the background. 
![with-dialog](https://user-images.githubusercontent.com/11473920/27519206-1bbc78aa-59ef-11e7-9ad5-0ba54c33e9a8.png)
![without-dialog](https://user-images.githubusercontent.com/11473920/27519207-1ec874c2-59ef-11e7-95b3-2b8fb95f1053.png)
