### ISSUE TITLE
Do not use heading-tags in search results

### ISSUE THREAD

**Issue by ccweb** [swiss/styleguide#496]
The six heading elements, H1 through H6, must be used to denote section headings.
&lt;h4&gt;&lt;a href="#"&gt;Title of the first result&lt;/a&gt;&lt;/h4&gt;
Remove the &lt;h4&gt;-tags and style the &lt;a&gt;-tags accordingly.

**Comment by bit-pro-iew-eui** [comment]
This issue can be implemented at the same time as #477, #515, #488

**Comment by angelogti** [comment]
Heading tags are still used as titles of the search results:

![image](https://user-images.githubusercontent.com/34123685/33759344-3fda30b6-dc02-11e7-9ca1-cbe37982c067.png)

(chrome, https://admin-ch.github.io/styleguide/en/search.html#07-search-02-search-results)
