### ISSUE TITLE
Bug in the mobile navigation?

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#500]
The navigation path global topic --> subtopic --> page does not seem to work correctly on smartphones. The bug was reported by a developer for www.ekas.admin.ch. Screenshots are attached. He found a workaround so the bug cannot be reproduced on the actual website. 
![ekas1](https://cloud.githubusercontent.com/assets/7466385/20702563/a0a2a984-b618-11e6-9b5d-34863db511e0.png)

![ekas2](https://cloud.githubusercontent.com/assets/7466385/20702614/d84bdb30-b618-11e6-867a-b97f2e6c159e.png)

![ekas3](https://cloud.githubusercontent.com/assets/7466385/20702612/d8494c94-b618-11e6-960a-db7bdb382b04.png)

![eka43](https://cloud.githubusercontent.com/assets/7466385/20702613/d84a7556-b618-11e6-8a6f-e0194b457a53.png)

**Comment by almeidap** [comment]
Issue cannot be reproduced. As far as I remember, this was a copy/paste issue which lead to duplicated sub menus.
