### ISSUE TITLE
Titelgrösse H1 zu gross

### ISSUE THREAD

**Issue by gs-uvek** [swiss/styleguide#505]
Titelgrösse H1 zu gross: H1 soll neu leicht kleiner definiert werden.

**Comment by mbruellmann** [comment]
Bitte präzisieren, weshalb das geändert werden soll und wie gross denn die "richtige" Grösse wäre. Danke.

**Comment by gs-uvek** [comment]
Je nach Titellänge kann es sein, dass dieser vier- oder gar fünfzeilig ausfällt (Beispiel: https://www.uvek.admin.ch/uvek/de/home/uvek/medien/medienmitteilungen.msg-id-65473.html), was sehr unschön ist. Zudem hat es teilweise auf einer Zeile nur Platz für ein Wort, wenn dieses länger ist. Die Reduktion der Grösse haben wir nicht definiert, so weit als möglich, so lange der Unterschied zu H2 deutlich ist.

**Comment by gs-ben** [comment]
M.E. ist das dann aber ein redaktionelles Problem. Ich finde nicht, dass das hier im Rahmen der Webguidelines gelöst werden muss.

**Comment by gs-uvek** [comment]
Die Schriftgrösse selber ist doch eine Vorgabe von CD-Bund? Redaktionell kann ja nur die Länge des Titels bestimmt werden.

**Comment by bit-pro-iew-eui** [comment]
Gemäss BK ist dieses Issue ein redaktionelles Problem (Überschriften zu lang).
