### ISSUE TITLE
Bessere Darstellung in der Komponente Sitemap

### ISSUE THREAD

**Issue by gs-uvek** [swiss/styleguide#506]
Die Unterscheidung der Titel von Hauptseite und Unterseiten ist auf den ersten Blick nicht deutlich. Die Abstände zwischen Hauptseiten- und Unterseitentitel sind gleich. 
![sitemap-beispiel-uvek](https://cloud.githubusercontent.com/assets/25457594/22738471/e036a3da-ee07-11e6-9f14-2bdafe0318d2.JPG)
Zumindest der Abstand vor den Hauptseitentiteln sollte vergrössert werden, damit klar ist, wann ein neues Hauptthema beginnt. Zudem könnte die Schriftgrösse angepasst werden (Hauptseitentitel grösser bzw. Untertitelseiten kleiner). In der Tablet-Ansicht ist die Unterscheidung besser sichtbar.

**Comment by bit-pro-iew-eui** [comment]
@gs-uvek in the web guideline (see here: [https://swiss.github.io/styleguide/de/footer.html#site-map]) the sitemap component has already what you request. Are you speaking about a component in your CMS Adobe Experience Manager?

![image](https://cloud.githubusercontent.com/assets/7510842/22742963/e42d0e00-ee18-11e6-9095-5c607bf6857c.png)

**Comment by gs-uvek** [comment]
Das ist der Footer der Seite ganz unten. Die automatisierte Komponente Sitemap ist normalerweise auf einer Flyout-Seite enthalten (https://www.uvek.admin.ch/uvek/de/home.html, dann auf "Das UVEK" klicken). Die Oberseiten müssen zudem auch verlinkt sein.

**Comment by bit-pro-iew-eui** [comment]
@gs-uvek I couldn't reproduce this issue, can you specify, which size of the browser window, browser, browser version?

**Comment by gs-uvek** [comment]
Desktop-Ansicht, Zoom 120%, IE11 und Firefox 45.6.0

Die umrahmten Titel des Screenshots sind Hauptkapitel, aber sie unterscheiden sich zuwenig von den Unterkapitel-Titeln:
![beispiel flyout 2](https://cloud.githubusercontent.com/assets/25457594/22779064/8141caf0-eeb9-11e6-9a12-25c41de736aa.JPG)

Auf 100% Zoom ist die Unterscheidung besser, aber die Abstände zwischen den Titeln sind generell gleich gross, was den Überblick erschwert.

**Comment by bit-pro-iew-eui** [comment]
ok, issue understood, answer pending.

**Comment by bit-pro-iew-eui** [comment]
Beim SIF und WBF ist implementiert wie gewünscht, generell es braucht keine Übersichtsseite, die Sitemap ist im Footer, wie oben schon erwähnt.
