### ISSUE TITLE
Teaser/Teaserliste: Einstellung Textdarstellung

### ISSUE THREAD

**Issue by gs-uvek** [swiss/styleguide#507]
Teaser/Teaserliste: Es soll eine Einstellung geben, dass der Text bündig weiterläuft und das Bild nicht umfliesst (das aktuelle Design bleibt als Variante weiter verfügbar). Dies wäre deshalb vorteilhaft, damit bei einer Teaserliste mit Bild der Text nicht teilweise unter dem Bild verläuft, teilweise nicht. Beispiel: 
![beispiel-teaserliste-bundiger-text](https://cloud.githubusercontent.com/assets/25457594/22738810/430b075c-ee09-11e6-80d5-77487a711a45.jpg)

**Comment by LeBenLeBen** [comment]
You can achieve this behavior using Bootstrap’s [media object](http://getbootstrap.com/components/#media) which is bundled with the styleguide.

**Comment by gs-uvek** [comment]
Bedeutet das einfach, dass diese Funktion (Text umfliesst Bild nicht, sondern läuft bündig weiter) laut CD Bund zulässig ist und keine CD-Bund-Anpassung nötig ist?
