### ISSUE TITLE
Bulletpoints in einer Bulletpoints-Liste

### ISSUE THREAD

**Issue by gs-uvek** [swiss/styleguide#509]
Innerhalb einer bullet-point-Aufzählung lassen sich keine weiteren bullet-point-Aufzählungszeichen darstellen, was neu möglich sein soll. Die bullet-points innerhalb von bullet-points werden zwar in der Komponente angezeigt, nach dem Schliessen der Komponente sind sie aber nicht mehr sichtbar. 
Beispiel (oben Backend, unten Frontend):
![bulletpoints in einer bulletpoints-liste](https://cloud.githubusercontent.com/assets/25457594/22739239/1bbe2772-ee0b-11e6-8bbe-e3cf57f06f66.jpg)

**Comment by bit-pro-iew-eui** [comment]
@gs-uvek is this text editor in your CMS Adobe Experience Manager?

**Comment by gs-uvek** [comment]
Ja

**Comment by bit-pro-iew-eui** [comment]
In one side, what appears in the text editor of the CMS AEM is out of our scope here. On the other side, we'll check if the definition of lists [here](https://swiss.github.io/styleguide/de/typography.html#04-typography-05-lists) should met your requirements.

**Comment by bit-pro-iew-eui** [comment]
Umsetzung in AEM entspricht den Vorgaben der Richtlinien. Siehe [hier](https://swiss.github.io/styleguide/de/typography.html#04-typography-05-lists)

**Comment by gs-uvek** [comment]
Ja, die AEM-Umsetzung entspricht den Richtlinien. Deswegen gibt es ja diesen Eintrag, um die CD-Bund-Richtlinie anzupassen und die Funktion (bullet-points in bullet-points) zu ermöglichen.
