### ISSUE TITLE
Titelgrösse in Brennpunkt-Komponente

### ISSUE THREAD

**Issue by gs-uvek** [swiss/styleguide#510]
Im Teaser wird der Titel vordefiniert als H4 angezeigt, wenn er ins Feld "Titel" eingefügt wird. Es sollte aber die Option bestehen, die Titelgrösse selber zu wählen, was momentan nur geht, wenn man den Titel unter "Teaser Text" pflegt. Dies hat aber zur Folge, dass der Abstand zwischen dem oberen Rand und dem Titel grösser wird. Beispiel einer Brennpunkt-Anzeige:
![beispiel brennpunkttitel](https://cloud.githubusercontent.com/assets/25457594/22739375/a649c40a-ee0b-11e6-869e-70019e2483be.JPG)

**Comment by bit-pro-iew-eui** [comment]
@gs-uvek are you speaking of functionality in your CMS Adobe Experience Manager?

**Comment by gs-uvek** [comment]
Gemeint ist eigentlich die Teaser-Komponente, die im Brennpunkt eingefügt ist:
![teaser brennpunkt](https://cloud.githubusercontent.com/assets/25457594/22743845/bac8ffd0-ee1b-11e6-90dc-de13c5a789ad.JPG)
Ich habe aber gerade festgestellt, dass laut CD Bund die Titelgrösse im Brennpunkt-Teaser doch nicht definiert ist (https://swiss.github.io/styleguide/de/teaser.html#05-teaser-01-focus), was ich übersehen habe. Ist das definitiv so? Falls ja könnte man den Issue schliessen.

**Comment by bit-pro-iew-eui** [comment]
ok, question understood, answer pending.

**Comment by bit-pro-iew-eui** [comment]
Bei Elementen auf  Übersicht-Seiten müssen die Titelgrössen (H1..Hn) manuell angepasst werden, damit die Seitestruktur semantisch übereinstimmt gemäss Barrierefreiheit-Vorgabe.
