### ISSUE TITLE
Der Lead soll die gleiche Schriftgrösse wie der Lauftext haben

### ISSUE THREAD

**Issue by gs-uvek** [swiss/styleguide#511]
Der Text, der momentan mit der Funktion im Texteditor „als Leadtext verwenden“ verwendet wird, ist kleiner, soll aber die gleiche Grösse wie der Lauftext haben. 
Beispiel (oben normaler Text mit bolt, unten Text mit Funktion "als Leadtext verwenden"):
![beispiel leadtext](https://cloud.githubusercontent.com/assets/25457594/22739469/117c373a-ee0c-11e6-8c5f-42c1c0b09681.JPG)

**Comment by bit-pro-iew-eui** [comment]
@gs-uvek do you speak about the Texteditor of the CMS in Adobe Experience Manager?

**Comment by gs-uvek** [comment]
Ja

**Comment by bit-pro-iew-eui** [comment]
This issue does not concern the web guideline itself, it concerns the **implementation** in your CMS, which it is out ouf our scope. We'll pass this issue to the CMS-Team in BIT. Closing issue.

**Comment by gs-uvek** [comment]
It is dealing with the Size of the lead in the Frontend. So it has to be solved in the Webguidelines first and not in the CMS. See also the Mail Exchange with Andre Junker from BIT.

**Comment by gs-uvek** [comment]
This is the Email exchange [AW Lead-Grösse.pdf](https://github.com/swiss/styleguide/files/2003685/AW.Lead-Grosse.pdf)
