### ISSUE TITLE
Cohérence dans l'apparence des liens internes et externes

### ISSUE THREAD

**Issue by csauser** [swiss/styleguide#522]
Selon qu'un lien interne ou externe est placé dans un flux de texte ou comme élément isolé, il apparaît souligné ou pas. [Exemple](https://www.bakom.admin.ch/bakom/fr/page-daccueil/medias-electroniques/diffusion-et-technique/diffusion-numerique/DAB-avenir-numerique-de-la-radio.html)

**Comment by mbruellmann** [comment]
Bitte Unterstreichung der Links im Text entfernen

**Comment by bit-pro-iew-eui** [comment]
@janissbinder please check if the links are underlined, if yes, please remove the underline for links
