### ISSUE TITLE
Homepage without global navigation ; News feed 4th column cutt off on ipad in portrait mode

### ISSUE THREAD

**Issue by ccweb** [swiss/styleguide#526]
On ipads the 4th column of the news feed is cut off at the right hand side in portrait screen orientation.
Apple iPad Air 2, 1536 x 2048 px
![ipad](https://cloud.githubusercontent.com/assets/7446943/24454882/e0373546-148d-11e7-82fd-5ec2fdb28d1b.png)

**Comment by janissbinder** [comment]
I cannot reproduce this error on the Homepage without global navigation. Normally there are only three columns and when I add a new one it looks on an IPad by default like this: 
![image](https://user-images.githubusercontent.com/5112014/32007029-ac2289ca-b9a8-11e7-9f54-3af05d86ef49.png)

@ccweb Could you please send me the URL where this Problem occurs on your Webpage?

**Comment by ccweb** [comment]
https://www.nkvf.admin.ch/nkvf/de/home.html or https://www.ejpd.admin.ch/ejpd/de/home.html
It it does not affect the Teaser but the News Feed component.

**Comment by janissbinder** [comment]
I'm really sorry but we aren't able to fix this because it isn't a stylguide issue. It looks like the problem comes from the relaunch.css which is included on both of your pages.

**Comment by ccweb** [comment]
I cannot reproduce this on our test system anymore.
