### ISSUE TITLE
Social sharing buttons werden nicht angezeigt

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#529]
Auf https://swiss.github.io/styleguide/de/functions.html#04-functions-02-social-sharing werden die Social sharing buttons nicht korrekt angezeigt (IE 11, FF 45.7.0)
![social-sharing-buttons](https://cloud.githubusercontent.com/assets/7466385/25438641/673acf54-2a9a-11e7-9e52-9a0de779d21f.PNG)

**Comment by q-src** [comment]
Closed in favor of #501
