### ISSUE TITLE
Missing images in build folder in npm package

### ISSUE THREAD

**Issue by Saphatonic** [swiss/styleguide#533]
Currently, there are references in the vendor.css to images which do not exist in the build/img folder.
The references are: 

- "../img/loading.gif"
- "../img/error.png"
- "../img/error.svg"
- "../img/play-pause.png"
- "../img/play-pause.svg"
- "../img/video-play.png"
- "../img/video-play.svg"

We are using a file loader with webpack, which throws an error because of the missing images. It would be nice if the npm package could be updated.

**Comment by bit-pro-iew-eui** [comment]
@gillerr Please check if the missing images are now fixed and no errors occur. Thx!
