### ISSUE TITLE
Focus of a subject in the primary navigation is partly covered.

### ISSUE THREAD

**Issue by rautenburger** [swiss/styleguide#549]
The focus of the different elements should always be at the very front and not be partly covered by other elements (image 1). This becomes a bigger issue when more containers are in place (image 2).

Image 1:
![image](https://user-images.githubusercontent.com/31723894/30901422-f99640fe-a367-11e7-9f41-e03987b1617a.png)

Image 2:
![covered subject](https://user-images.githubusercontent.com/31723894/30901644-f5c0598c-a368-11e7-812d-d308b9a41d53.png)

Tested on: 
https://q-src.github.io/styleguide/de/
Tested with:
NVDA screen reader

**Comment by angelogti** [comment]
The focus indicator is still partly covered when a menu item/tab is expanded. Is it a feature or a bug?

![image](https://user-images.githubusercontent.com/34123685/33758865-6d042ada-dc00-11e7-8f15-97247ad68c2c.png)


tested with chrome on : https://admin-ch.github.io/styleguide/en/pages/06.detail.html
