### ISSUE TITLE
The source code is not navigable using the keyboard

### ISSUE THREAD

**Issue by rautenburger** [swiss/styleguide#553]
The source code is not navigable using the keyboard - not with tab not with arrow keys. 

Tested on:
https://q-src.github.io/styleguide/en/
Tested with:
NVDA screen reader

**Comment by bit-pro-iew-eui** [comment]
Source code is navigable with enter, please specify if code is read by screenreader-

**Comment by rautenburger** [comment]
The source code is not navigable in Chrome (Version 58.0.3029.110)

**Comment by bit-pro-iew-eui** [comment]
Source code is navigable but is not read by the browser Chrome, this works correctly in FireFox

**Comment by bit-pro-iew-eui** [comment]
Works good.
