### ISSUE TITLE
missing images

### ISSUE THREAD

**Issue by thomome** [swiss/styleguide#556]
The following images are missing (referenced in styleguide/build/css/vendors.css):

- styleguide/build/img/error.png
- styleguide/build/img/error.svg
- styleguide/build/img/loading.gif
- styleguide/build/img/play-pause.png
- styleguide/build/img/play-pause.svg
- styleguide/build/img/video-play.png
- styleguide/build/img/video-play.svg

**Comment by bit-pro-iew-eui** [comment]
Duplicate off #533
