### ISSUE TITLE
Icons - missing release translation and title release in the wrong place

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#590]
![image](https://user-images.githubusercontent.com/7510842/32652390-6381ee32-c604-11e7-9fb2-8fec86cee35f.png)

Tested on Chrome   61.0.3163.100
https://swiss.github.io/styleguide/de/general.html#02-general-08-icons

**Comment by gillerr** [comment]
This is simply a translation issue. Text in French and German and possibly English as well are not correct
