### ISSUE TITLE
"Breadcrumb" announcement is not read by the screenreader

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#595]
The announcement of "breadcrumb" is not read by the screenreader. The problem is that in the class .hidden the "display:none" causes the screenreader to skip it. The solution is this:

![image](https://user-images.githubusercontent.com/7510842/32947703-923b49ba-cb9c-11e7-995d-4013892bd716.png)

https://swiss.github.io/styleguide/de/hierarchical-navigation.html#01-hierarchical-navigation-02-breadcrumb

**Comment by gillerr** [comment]
use `sr-only` class instead of `hidden` class

**Comment by gillerr** [comment]
The title with `hidden` class is the target of an `aria-labelledby` attribute. It will be read even if not displayed

**Comment by bit-pro-iew-eui** [comment]
Ok, validated
