### ISSUE TITLE
Color contrast in table caption tags are not AA conform

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#597]
The text color in the table caption tags in all tables have the color "#999" this color has not sufficient contrast. Change the color for the table captions to #454545 ($coal).

![image](https://user-images.githubusercontent.com/7510842/32949288-a0587328-cba2-11e7-941e-9f36b275cc96.png)

https://swiss.github.io/styleguide/de/tables.html

**Comment by gillerr** [comment]
This color applies to the `text-muted` class. This class can be used standalone and as a basis for `caption`s as well as headings and `blockquote`s `small` part.
Should only `caption`s be changed to the `coal` color or the whole `text-muted` class?

**Comment by gillerr** [comment]
Actually, `coal`is the default color for texts

**Comment by bit-pro-iew-eui** [comment]
Ok
