### ISSUE TITLE
Collapsible panel is not navigable with tab

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#598]
Collapsible panel is not navigable with tab. Please implement accordingly:

![image](https://user-images.githubusercontent.com/7510842/32950749-c86fd52c-cba7-11e7-92d7-93479b9c20aa.png)

https://swiss.github.io/styleguide/de/content-containers.html#02-content-containers-03-collapsible-panel

**Comment by gillerr** [comment]
Each collapsible panels and each actionable element within an open collapsible panel have to be accessible with tab key

**Comment by gillerr** [comment]
The current behavior is a feature of bootstrap-accessibility-plugin
http://paypal.github.io/bootstrap-accessibility-plugin/demo.html#collapse

I recommend removing the accordion behavior for a better usability

**Comment by bit-pro-iew-eui** [comment]
Ok, it works
