### ISSUE TITLE
Social media standard image accessibility tag with Alt instead of aria labels

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#603]
Please use alt-attribute instead of aria-label to describe the social icon-image. 

Label: Share to [social media name here]

![image](https://user-images.githubusercontent.com/7510842/33371090-e3ff3c32-d4f9-11e7-969a-6612e3120aca.png)

**Comment by gillerr** [comment]
Social sharing icons are applied as a CSS background of an `a` tag and not as an `img` tag. 
`alt` attribute can only be applied to `img` tag and will be ignored on other tags.
The `aria-label` is thus a correct solution, but could be replaced with a `title` attribute. This will still be read by screen readers as the `a` have no content. And the `title` value will be displayed on mouse over.

**Comment by bit-pro-iew-eui** [comment]
Guideline ok.
Implementation in www.eak.admin.ch was done with img, the alt-tag is empty there. 
See https://www.eak.admin.ch/eak/de/home/Firmen/Anschluss.html

![image](https://user-images.githubusercontent.com/7510842/33762006-4d532dd4-dc0b-11e7-8298-6ad2a912a92a.png)
 Closing issue
