### ISSUE TITLE
Add Title-Attribute to <a> Tag so that Screen Reader Anounces As External Link

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#605]
Please add the 'title' attribute to the external link title='External link', so that screen reader anounces external link

https://swiss.github.io/styleguide/de/typography.html#04-typography-08-links

![image](https://user-images.githubusercontent.com/7510842/33373972-801ac3a2-d504-11e7-8565-8d6f8aaced4e.png)

**Comment by gillerr** [comment]
With chromeVox, links starting with `#` will be announced 

> internal link

And other links will be announced

> link

`title` attribute is ignored
