### ISSUE TITLE
Code Appears next to the Headers in the Print Version of the Page

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#607]
Example collapsible panel appears "nel (#02-content-containers-03-collapsible-panel)" next to the title, in the print version when Ctrl+P is pressed.

![image](https://user-images.githubusercontent.com/7510842/33420382-a050f6dc-d5ae-11e7-936f-5ec9db00a197.png)

Link
https://swiss.github.io/styleguide/en/content-containers.html#02-content-containers-03-collapsible-panel
Chrome

**Comment by gillerr** [comment]
It's a feature, not a bug. 
In print mode a CSS rule is applied to all links (not only headers) to display the target of the link.
