### ISSUE TITLE
In desktop view, zooming 170% appears Navigation link 

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#608]
The navigation link shouldn't be present, because it is an element for a mobile device.
Here the original description:

![image](https://user-images.githubusercontent.com/7510842/33486288-be61f238-d6a9-11e7-87d8-a8d7bf6c05c2.png)
![image](https://user-images.githubusercontent.com/7510842/33486320-e1377850-d6a9-11e7-98ad-f95ce7976745.png)

**Comment by bit-pro-iew-eui** [comment]
@almeidap Please make an analysis first. Thx!

**Comment by bit-pro-iew-eui** [comment]
@angelogti Please describe the steps needed to reproduce issue, thx!

**Comment by angelogti** [comment]
- go to: https://swiss.github.io/styleguide/de/pages/06.detail.html#site-map
- zoom to 170 %
- a link "context sidebar" appears.
![image](https://user-images.githubusercontent.com/34123685/33607659-25bbc100-d9c2-11e7-8ecd-0495f4b25b06.png)


 Clicking on it only scrolls down the page:


![image](https://user-images.githubusercontent.com/34123685/33607728-4ab3c2c8-d9c2-11e7-9bc5-04a43cd33363.png)

Furthermore, the "Sitemap" link at the end of the page opens the footer navigation, just like they describe in the report (I imagine it is its normal behaviour, but for them it's a problem).

**Comment by gillerr** [comment]
The link "Context sidebar" appears as soon as the layout changes from 3 columns to 2 columns, pushing the context sidebar below the normal content. This is normal behavior on tablet for instance. Zooming on such levels will trigger tablet view.

The "Sitemap" link on the other end have been replaced with a "Sitemap" button to express that no page change will occur
