### ISSUE TITLE
Color Contrast in Some Elements are not AA Conform

### ISSUE THREAD

**Issue by bit-pro-iew-eui** [swiss/styleguide#609]
- [x] All over the webguideline the text color of "Example" ans "</>" has not enough contrast, change color to $empress, #757575
![image](https://user-images.githubusercontent.com/7510842/33603784-08726292-d9b4-11e7-8622-82abda505081.png)

- [x] Text-muted class color has not enough contrast, change color to $empress, #757575

- [x] Check if classes small and blockquote  have enough contrast, at least AA

**Comment by gillerr** [comment]
`blockquote` already uses `$empress` for font color, therefore `<small>` will have the same color. But `<small>` should not be used within `blockquote` because of the double quotes added before and after the text.

**Comment by bit-pro-iew-eui** [comment]
Validated, contrast ok AA
