### ISSUE TITLE
Webpack build fails because of missing images

### ISSUE THREAD

**Issue by patbrant** [swiss/styleguide#629]
I installed the package swiss-styleguide via npm. While starting the application with angular-cli I am getting the error that following files are missing:

error.png
error.svg
loading.gif
play-pause-png
play-pause.svg
video-play.png
video-play.svg

I think it is because the images of the bower component blueimp-gallery are not beeing copied during gulp build (gulptask: build-images). It looks like it's fixed on the newest version on master-branch but i can't download this version from npm yet. Without this images I can't build the application.

**Comment by gillerr** [comment]
fixed on master, will be published with next version
