### ISSUE TITLE
Twitter Timeline internationalization

### ISSUE THREAD

**Issue by bgrand** [swiss/styleguide#640]
https://github.com/swiss/styleguide/blob/45603d74b3479883104f47324b6eb83bd0a83b8d/src/assets/js/twitter-timeline.js#L25
Is there any parameter for Twitter Timeline internationalization ? There is a param "lang" for other Twitter widgets, but I didn't found it for Timeline. Does someone know something more about it ?

**Comment by gillerr** [comment]
Issue will be closed due to inactivity

**Comment by gillerr** [comment]
Close due to inactivity
