### ISSUE TITLE
Missing heading class

### ISSUE THREAD

**Issue by fkm** [swiss/styleguide#643]
https://github.com/swiss/styleguide/blob/45603d74b3479883104f47324b6eb83bd0a83b8d/src/assets/sass/layout/titles.scss#L16

As this style guide is based on Bootstrap, all your heading definitions should (must?) include the respective classes.

Here, we need `.h4` in addition to `h4`.

Docs: https://getbootstrap.com/docs/3.3/css/#type-headings

**Comment by gillerr** [comment]
No, both options yields the same result, they are not meant to be used together.
Anyway, this will be solved with the migration to Material Design
Issue will be closed

**Comment by fkm** [comment]
I just hope you'll do a better job with the Material Design implementation than you did with Bootstrap.
