### ISSUE TITLE
IE 11"alert alert-warning" class icon is too big

### ISSUE THREAD

**Issue by Saphatonic** [swiss/styleguide#645]
When we are using the" alert alert-warning" class like this

    <div class="alert alert-warning" role="alert">
        <strong>Es gibt noch eine weitere Bestellung in diesem Zeitbereich</strong>
    </div>

the exclamation mark icon appears bigger in IE than in Firefox or Chrome. I think this is caused by using em in the stylesheet. I have temporarily fixed the issues by overwriting the css to use rem instead of em.

Firefox: 
![image](https://user-images.githubusercontent.com/13716816/38296948-44ebcacc-37f3-11e8-9979-1327576ab981.png)

IE 11:
![image](https://user-images.githubusercontent.com/13716816/38296977-5752472c-37f3-11e8-97a2-d3c948fd4f87.png)

**Comment by gillerr** [comment]
Cannot reproduce
on https://swiss.github.io/styleguide/en/widgets.html#03-widgets-01-alerts, warning alerts are displayed correctly with IE11
Issue will be closed

**Comment by gillerr** [comment]
Cannot reproduce
