### ISSUE TITLE
Footer sitemap is empty on MD when opening and closing on SM 

### ISSUE THREAD

**Issue by 1stthomas** [swiss/styleguide#650]
Steps to reproduce:
- Open page https://www.admin.ch/gov/de/start.html on MD viewport
- compress the browser to SM viewport
- open the sitemap
- close the sitemap
- enlarge the browser to MD viewport
- look for the sitemap in the footer -> the sitemap is empty

remarks:
- if you have the sitemap open on SM and enlarge the browser to MD, the sitemap will be visible.
- If you compress the viewport from MD to SM, the sitemap is by default closed. Therfor I expect, that the sitemap should be visible, when I close it on SM and enlarge the browser viewport to MD.

**Comment by gillerr** [comment]
What do you mean by "open the sitemap"?

**Comment by 1stthomas** [comment]
I think the content in the container with the class `site-map` was in a collapse block when writing this issue. But now when I open several pages on admin.ch, I can not replicate this issue, because all content from the sitemap is not collapsed.

Therefor i will close this issue.
