### ISSUE TITLE
Is this project active - will it be upgraded to bootstrap 4 ?

### ISSUE THREAD

**Issue by ytsurk** [swiss/styleguide#656]
The swiss styleguide seems not to be actively maintained .. I see recent issues,
but no commit since 2 years.

I wonder if there will be a bootstrap 4 version ?

**Comment by gillerr** [comment]
We are actually discussing the future of the styleguide with the federal chancellery. Current options are:
* migrate to Bootstrap 4
* migrate to Bootstrap 5
* migrate to Material Design
* Going technology agnostic

This means, nothing will be done until the situation is clarified.

**Comment by ytsurk** [comment]
I vote for Bootstrap 5 ;)

**Comment by gillerr** [comment]
It will be migrate to Material Design.
Issue will be closed

**Comment by bschaeublin** [comment]
@gillerr Will this repo still be used for the "Material Design" version?
Is it possible to contribute to this migration?

**Comment by gillerr** [comment]
@bschaeublin yes, this repo will still be used. The migration will be done by the BIT, but you are welcome to share your ideas on https://github.com/swiss/styleguide/issues/657
