### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by psytraxx** [swiss/styleguide#660]
Hi Guys,
we use this npm in one of our client  projects (Bundesamt für Informatik und Telekommunikation BIT) 
They did a RAST scan and want to fix the bootstrap version (current 3.3.6 --> latest 3.3.7) We are using version 3.0.0 from the npm but there seems to be a newer version 3.2.0 too - how can i use it?
Is this project still actively maintained? 
If not - are there alternatives ?
Thanks so much for your help
Eric

**Comment by Soardiac** [comment]
see here: https://github.com/swiss/styleguide/issues/661

**Comment by psytraxx** [comment]
Great - thank you!
